#!/usr/bin/env bash

# Add repositories/ppas
add-apt-repository -y ppa:chris-lea/node.js

# Update repository information
apt-get update

# Install essential 
apt-get install -y git vim nodejs postgresql postgresql-contrib

# Clone project files
git clone http://github.com/varunjyoti/tripgang-client /vagrant/tripgang-client 
git clone http://github.com/varunjyoti/tripgang-server /vagrant/tripgang-server && cd /vagrant/tripgang-server && npm install
